#/********************
#Jeffrey-David Kapp
#0832671
#CIS2520 Assignment 2
#14 Oct 2014
#********************/

all:
	gcc -Wall -g -Iinclude src/q1/* -o bin/q1
	#gcc -Wall -g -Iinclude src/q2/* -o bin/q2