/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_example */

#ifndef _Included_JNI_example
#define _Included_JNI_example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_example
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1example_printHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
