/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gui_Dialogc */

#ifndef _Included_gui_Dialogc
#define _Included_gui_Dialogc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gui_Dialogc
 * Method:    compile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Dialogc_compile
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
